name: Deploy Backend to Cloud Run

on:
  push:
    branches: [jack.nguyen]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUD_RUN_SERVICE: Domain-Validator-NodeJS
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Build Docker image
        run: |
          gcloud builds submit --tag asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/$CLOUD_RUN_SERVICE ./backend
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $CLOUD_RUN_SERVICE \
            --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/$CLOUD_RUN_SERVICE \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars NODE_ENV=production,PORT=8080